import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import StoreProvider from "@/providers/StoreProvider";
import HeaderCart from "@/components/Cart/HeaderCart/HeaderCart";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <StoreProvider>
          <header
            style={{
              display: "flex",
              justifyContent: "space-between",
              gap: "20px",
              borderBottom: "1px solid",
              padding: "20px 0",
            }}
          >
            <Link href={"/"}>Booknest</Link>
            <div
              className="nav"
              style={{
                display: "flex",
                justifyContent: "space-between",
                gap: "20px",
              }}
            >
              <Link href={"/admin"}>Admin</Link>
              <Link href={"/books"}>Books</Link>
            </div>
            <HeaderCart />
          </header>
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
