import "./globals.css";

import type { Metadata } from "next";
import { Roboto_Flex, Inter } from "next/font/google";
import StoreProvider from "@/providers/StoreProvider";
import ThemeProvider from "@/providers/ThemeProvider";
import { SessionProvider } from "next-auth/react";
import Header from "@/components/Header/Header";

const robotoFlex = Roboto_Flex({
  variable: "--font-content",
  subsets: ["latin", "cyrillic"],
});

const inter = Inter({
  variable: "--font-ui",
  subsets: ["latin", "cyrillic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const noFlashScript = `
(function() {
  try {
    var stored = localStorage.getItem('theme');
    var theme = stored === 'light' || stored === 'dark'
      ? stored
      : (window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light');
    document.documentElement.setAttribute('data-theme', theme);
  } catch (e) {}
})();
`;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${robotoFlex.variable} ${inter.variable}`}>
      <body>
        <script dangerouslySetInnerHTML={{ __html: noFlashScript }} />
        <SessionProvider>
          <ThemeProvider>
            <StoreProvider>
              <Header />
              <div className="container pageContent">
                {children}
              </div>
            </StoreProvider>
          </ThemeProvider>
        </SessionProvider>
      </body>
    </html>
  );
}